### ISSUE TITLE
Climate entries don't show up

### ISSUE THREAD

**Issue by thomasklingbeil** [markusressel/XS1_HA#1]
First of all: Thanks for you work!
Using Homeassistant 0.52.1, the climate entries properly show up and also the internal and friendly names of the devices match.

<img width="313" alt="screen shot 2017-12-31 at 4 21 16 pm" src="https://user-images.githubusercontent.com/190958/34462553-a99a4904-ee46-11e7-9708-f874e326fd65.png">

With **Homeassistant 0.60** (even when running at the same time), no climate devices are visible. 
Also the internal and friendly names are mixed up between different devices. It seems that the friendly name is the correct one. Are the missing climate devices maybe related to this?

<img width="494" alt="screen shot 2017-12-31 at 4 19 29 pm" src="https://user-images.githubusercontent.com/190958/34462546-7fbcbb4e-ee46-11e7-8e93-f2c5ff50ed74.png">

Please let me know, if I can help somehow!

**Comment by thomasklingbeil** [comment]
I just realized the log is full of those errors

> 2017-12-31 16:12:07 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
>     result = coro.send(None)
>   File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 399, in async_process_entity
>     new_entity, self, update_before_add=update_before_add
>   File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 247, in async_add_entity
>     yield from entity.async_update_ha_state()
>   File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
>     attr)
>   File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 333, in _attr_setter
>     value = getattr(self, name)
>   File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 736, in supported_features
>     raise NotImplementedError()
> NotImplementedError

**Comment by thomasklingbeil** [comment]
The issue regarding the climate component is fixed in PR #2.
The problem regarding the mixup seems to derive form a mixup in the underlying library: https://github.com/markusressel/xs1-api-client/issues/1

As a hotfix for now, I have just called update() on all the sensors and actuators before the actual HA components have been created.

**Comment by markusressel** [comment]
Thx for the PR. I'm closing this issue as the original problem is fixed now.
See https://github.com/markusressel/xs1-api-client/issues/1 for more info on the id mixup problem.
